version: '3.8'
services:
  gateway:
    build: ./gateway
    image: shareit-gateway
    container_name: gateway-host
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:8080

  server:
    build: ./server
    image: shareit-server
    container_name: server-host
    ports:
      - "9090:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USER=test
      - SPRING_DATASOURCE_PASSWORD=test

  db:
    image: "postgres:13.7-alpine"
    container_name: shareit-db
    volumes:
      - /var/lib/postgresql/db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test